//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/InputSystem/BaseControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @BaseControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @BaseControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""BaseControls"",
    ""maps"": [
        {
            ""name"": ""PlayerMap"",
            ""id"": ""8e87bbc1-fd86-4ad8-bea2-f89178c76f97"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""d58270cc-77d1-4764-9051-9f8d81b13ff1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""740b8332-5c64-46e6-868c-3c0e78a7ca0d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AimMode"",
                    ""type"": ""Button"",
                    ""id"": ""0256b432-7b75-44df-9c31-628e8bdecf33"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FireProjectile"",
                    ""type"": ""Button"",
                    ""id"": ""3f878c0f-e1b7-49fd-80ab-4e8948c707ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grapple"",
                    ""type"": ""Button"",
                    ""id"": ""aca5162f-9a33-4e41-b9ec-0a5f40ec61c1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Button"",
                    ""id"": ""9f2086fe-fef0-4b0d-9211-ec09cd4a65e4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenMenu"",
                    ""type"": ""Button"",
                    ""id"": ""feed6d72-3d90-43bd-a481-e79a317c9c21"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenDevMenu"",
                    ""type"": ""Button"",
                    ""id"": ""6db1c13b-14e3-433a-a29d-1ec1abe0eb47"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenMap"",
                    ""type"": ""Button"",
                    ""id"": ""b077b79f-2a64-4332-9c0e-2c88d163b27c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Arrow Keys"",
                    ""id"": ""20427ad2-42bb-43ff-a265-7ce3e8e2e0d4"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a7a3416e-7e90-441e-88a9-d3473bc5583b"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d2f55ae8-8774-4f4a-85a3-e9f62ed2d906"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""88e3d780-1770-4aa2-a98e-454f29aaf6b0"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b906301f-5c54-4c4e-bce3-305aae39cc68"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""bde62143-405d-4457-9233-c65871c6938d"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2eba869f-c807-4e07-924c-d3fdb0204370"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3039bf0c-e243-4f1c-b830-f1fff9015699"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3f91004-fc5d-4395-8c99-adda1bed039f"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e78e9ce-8c4d-4a3d-8b0d-cea9d472e63d"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c4cf6abc-a3ff-43c7-b94b-62a21f003085"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FireProjectile"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b90cd4e7-80a1-4f20-9e05-4ef53568bf76"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FireProjectile"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9ab4152-2c01-45b5-a79a-59cf93121b4c"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grapple"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a53f87c-fb86-4cd3-9fa2-3bc3c4dda3f0"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grapple"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""430fdc12-231d-4c1e-a345-52e4eeee29aa"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ca9e00b5-1f0b-4d19-b5bc-efb19570b4e3"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99c45ff8-f0f6-4d57-82c8-d85767b1c25a"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0eebfda1-dbcc-4bc9-9ec0-9e479d87dc8f"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""597af277-7374-4ec7-9c08-a67e050540eb"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenDevMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""03b871eb-d39d-4fe2-8cae-0132cb571b8f"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenDevMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f2a98a6-76fa-48eb-a8a9-f06513d5fd65"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ffc4cb77-9701-48e3-84d3-c994e61d5cfa"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""TestMap"",
            ""id"": ""c98d2327-78fe-457b-8284-2eac118f7720"",
            ""actions"": [
                {
                    ""name"": ""Vector2"",
                    ""type"": ""Value"",
                    ""id"": ""97b62e99-a235-4af0-a2f7-7f354e70173c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a7b0cd6c-6fc0-4fe2-a99e-c60a2bb4e334"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""Vector2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PauseMap"",
            ""id"": ""99e86a9f-193b-477e-94a4-c8d7d44a6a3a"",
            ""actions"": [
                {
                    ""name"": ""CloseMenu"",
                    ""type"": ""Button"",
                    ""id"": ""5d61c59f-deec-4419-a132-a8a1f2abe815"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ea718209-8cbe-4ea2-a349-ec9dd849917a"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37e4b592-762e-4836-89c4-814be2098a36"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MapMap"",
            ""id"": ""f78c3a48-2bc0-4a48-9261-1bd9edc6507f"",
            ""actions"": [
                {
                    ""name"": ""CloseMap"",
                    ""type"": ""Button"",
                    ""id"": ""a08febd0-00ac-42cb-969f-9738a28dd964"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScrollMap"",
                    ""type"": ""Value"",
                    ""id"": ""3e8495e9-31bb-4c0a-8ceb-8ca6a6d2a4fe"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""114a15bd-a842-4bc9-a7f9-4e28ff02d7c5"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f263fa0f-8d93-40fe-a800-8e394465ff7a"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e4ee0fc-f07b-43e7-9ba5-2966f63f391a"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Arrow Keys"",
                    ""id"": ""61fbd0c8-3920-45de-b5dd-ffc14d6a0cfe"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollMap"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""04ae9ca1-f9fb-483a-bba9-c89c90fa38ca"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""76f4f95c-82e4-488e-8d8b-f651162edc5c"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0c7c3a87-ca85-4950-9db9-535825499abb"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b0b9ccce-0276-4b4b-8425-9a1e42d9111a"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerMap
        m_PlayerMap = asset.FindActionMap("PlayerMap", throwIfNotFound: true);
        m_PlayerMap_Move = m_PlayerMap.FindAction("Move", throwIfNotFound: true);
        m_PlayerMap_Sprint = m_PlayerMap.FindAction("Sprint", throwIfNotFound: true);
        m_PlayerMap_AimMode = m_PlayerMap.FindAction("AimMode", throwIfNotFound: true);
        m_PlayerMap_FireProjectile = m_PlayerMap.FindAction("FireProjectile", throwIfNotFound: true);
        m_PlayerMap_Grapple = m_PlayerMap.FindAction("Grapple", throwIfNotFound: true);
        m_PlayerMap_Rotate = m_PlayerMap.FindAction("Rotate", throwIfNotFound: true);
        m_PlayerMap_OpenMenu = m_PlayerMap.FindAction("OpenMenu", throwIfNotFound: true);
        m_PlayerMap_OpenDevMenu = m_PlayerMap.FindAction("OpenDevMenu", throwIfNotFound: true);
        m_PlayerMap_OpenMap = m_PlayerMap.FindAction("OpenMap", throwIfNotFound: true);
        // TestMap
        m_TestMap = asset.FindActionMap("TestMap", throwIfNotFound: true);
        m_TestMap_Vector2 = m_TestMap.FindAction("Vector2", throwIfNotFound: true);
        // PauseMap
        m_PauseMap = asset.FindActionMap("PauseMap", throwIfNotFound: true);
        m_PauseMap_CloseMenu = m_PauseMap.FindAction("CloseMenu", throwIfNotFound: true);
        // MapMap
        m_MapMap = asset.FindActionMap("MapMap", throwIfNotFound: true);
        m_MapMap_CloseMap = m_MapMap.FindAction("CloseMap", throwIfNotFound: true);
        m_MapMap_ScrollMap = m_MapMap.FindAction("ScrollMap", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerMap
    private readonly InputActionMap m_PlayerMap;
    private IPlayerMapActions m_PlayerMapActionsCallbackInterface;
    private readonly InputAction m_PlayerMap_Move;
    private readonly InputAction m_PlayerMap_Sprint;
    private readonly InputAction m_PlayerMap_AimMode;
    private readonly InputAction m_PlayerMap_FireProjectile;
    private readonly InputAction m_PlayerMap_Grapple;
    private readonly InputAction m_PlayerMap_Rotate;
    private readonly InputAction m_PlayerMap_OpenMenu;
    private readonly InputAction m_PlayerMap_OpenDevMenu;
    private readonly InputAction m_PlayerMap_OpenMap;
    public struct PlayerMapActions
    {
        private @BaseControls m_Wrapper;
        public PlayerMapActions(@BaseControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PlayerMap_Move;
        public InputAction @Sprint => m_Wrapper.m_PlayerMap_Sprint;
        public InputAction @AimMode => m_Wrapper.m_PlayerMap_AimMode;
        public InputAction @FireProjectile => m_Wrapper.m_PlayerMap_FireProjectile;
        public InputAction @Grapple => m_Wrapper.m_PlayerMap_Grapple;
        public InputAction @Rotate => m_Wrapper.m_PlayerMap_Rotate;
        public InputAction @OpenMenu => m_Wrapper.m_PlayerMap_OpenMenu;
        public InputAction @OpenDevMenu => m_Wrapper.m_PlayerMap_OpenDevMenu;
        public InputAction @OpenMap => m_Wrapper.m_PlayerMap_OpenMap;
        public InputActionMap Get() { return m_Wrapper.m_PlayerMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerMapActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerMapActions instance)
        {
            if (m_Wrapper.m_PlayerMapActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnMove;
                @Sprint.started -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnSprint;
                @Sprint.performed -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnSprint;
                @Sprint.canceled -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnSprint;
                @AimMode.started -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnAimMode;
                @AimMode.performed -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnAimMode;
                @AimMode.canceled -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnAimMode;
                @FireProjectile.started -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnFireProjectile;
                @FireProjectile.performed -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnFireProjectile;
                @FireProjectile.canceled -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnFireProjectile;
                @Grapple.started -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnGrapple;
                @Grapple.performed -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnGrapple;
                @Grapple.canceled -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnGrapple;
                @Rotate.started -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnRotate;
                @Rotate.performed -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnRotate;
                @Rotate.canceled -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnRotate;
                @OpenMenu.started -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnOpenMenu;
                @OpenMenu.performed -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnOpenMenu;
                @OpenMenu.canceled -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnOpenMenu;
                @OpenDevMenu.started -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnOpenDevMenu;
                @OpenDevMenu.performed -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnOpenDevMenu;
                @OpenDevMenu.canceled -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnOpenDevMenu;
                @OpenMap.started -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnOpenMap;
                @OpenMap.performed -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnOpenMap;
                @OpenMap.canceled -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnOpenMap;
            }
            m_Wrapper.m_PlayerMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Sprint.started += instance.OnSprint;
                @Sprint.performed += instance.OnSprint;
                @Sprint.canceled += instance.OnSprint;
                @AimMode.started += instance.OnAimMode;
                @AimMode.performed += instance.OnAimMode;
                @AimMode.canceled += instance.OnAimMode;
                @FireProjectile.started += instance.OnFireProjectile;
                @FireProjectile.performed += instance.OnFireProjectile;
                @FireProjectile.canceled += instance.OnFireProjectile;
                @Grapple.started += instance.OnGrapple;
                @Grapple.performed += instance.OnGrapple;
                @Grapple.canceled += instance.OnGrapple;
                @Rotate.started += instance.OnRotate;
                @Rotate.performed += instance.OnRotate;
                @Rotate.canceled += instance.OnRotate;
                @OpenMenu.started += instance.OnOpenMenu;
                @OpenMenu.performed += instance.OnOpenMenu;
                @OpenMenu.canceled += instance.OnOpenMenu;
                @OpenDevMenu.started += instance.OnOpenDevMenu;
                @OpenDevMenu.performed += instance.OnOpenDevMenu;
                @OpenDevMenu.canceled += instance.OnOpenDevMenu;
                @OpenMap.started += instance.OnOpenMap;
                @OpenMap.performed += instance.OnOpenMap;
                @OpenMap.canceled += instance.OnOpenMap;
            }
        }
    }
    public PlayerMapActions @PlayerMap => new PlayerMapActions(this);

    // TestMap
    private readonly InputActionMap m_TestMap;
    private ITestMapActions m_TestMapActionsCallbackInterface;
    private readonly InputAction m_TestMap_Vector2;
    public struct TestMapActions
    {
        private @BaseControls m_Wrapper;
        public TestMapActions(@BaseControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Vector2 => m_Wrapper.m_TestMap_Vector2;
        public InputActionMap Get() { return m_Wrapper.m_TestMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TestMapActions set) { return set.Get(); }
        public void SetCallbacks(ITestMapActions instance)
        {
            if (m_Wrapper.m_TestMapActionsCallbackInterface != null)
            {
                @Vector2.started -= m_Wrapper.m_TestMapActionsCallbackInterface.OnVector2;
                @Vector2.performed -= m_Wrapper.m_TestMapActionsCallbackInterface.OnVector2;
                @Vector2.canceled -= m_Wrapper.m_TestMapActionsCallbackInterface.OnVector2;
            }
            m_Wrapper.m_TestMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Vector2.started += instance.OnVector2;
                @Vector2.performed += instance.OnVector2;
                @Vector2.canceled += instance.OnVector2;
            }
        }
    }
    public TestMapActions @TestMap => new TestMapActions(this);

    // PauseMap
    private readonly InputActionMap m_PauseMap;
    private IPauseMapActions m_PauseMapActionsCallbackInterface;
    private readonly InputAction m_PauseMap_CloseMenu;
    public struct PauseMapActions
    {
        private @BaseControls m_Wrapper;
        public PauseMapActions(@BaseControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @CloseMenu => m_Wrapper.m_PauseMap_CloseMenu;
        public InputActionMap Get() { return m_Wrapper.m_PauseMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PauseMapActions set) { return set.Get(); }
        public void SetCallbacks(IPauseMapActions instance)
        {
            if (m_Wrapper.m_PauseMapActionsCallbackInterface != null)
            {
                @CloseMenu.started -= m_Wrapper.m_PauseMapActionsCallbackInterface.OnCloseMenu;
                @CloseMenu.performed -= m_Wrapper.m_PauseMapActionsCallbackInterface.OnCloseMenu;
                @CloseMenu.canceled -= m_Wrapper.m_PauseMapActionsCallbackInterface.OnCloseMenu;
            }
            m_Wrapper.m_PauseMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @CloseMenu.started += instance.OnCloseMenu;
                @CloseMenu.performed += instance.OnCloseMenu;
                @CloseMenu.canceled += instance.OnCloseMenu;
            }
        }
    }
    public PauseMapActions @PauseMap => new PauseMapActions(this);

    // MapMap
    private readonly InputActionMap m_MapMap;
    private IMapMapActions m_MapMapActionsCallbackInterface;
    private readonly InputAction m_MapMap_CloseMap;
    private readonly InputAction m_MapMap_ScrollMap;
    public struct MapMapActions
    {
        private @BaseControls m_Wrapper;
        public MapMapActions(@BaseControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @CloseMap => m_Wrapper.m_MapMap_CloseMap;
        public InputAction @ScrollMap => m_Wrapper.m_MapMap_ScrollMap;
        public InputActionMap Get() { return m_Wrapper.m_MapMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MapMapActions set) { return set.Get(); }
        public void SetCallbacks(IMapMapActions instance)
        {
            if (m_Wrapper.m_MapMapActionsCallbackInterface != null)
            {
                @CloseMap.started -= m_Wrapper.m_MapMapActionsCallbackInterface.OnCloseMap;
                @CloseMap.performed -= m_Wrapper.m_MapMapActionsCallbackInterface.OnCloseMap;
                @CloseMap.canceled -= m_Wrapper.m_MapMapActionsCallbackInterface.OnCloseMap;
                @ScrollMap.started -= m_Wrapper.m_MapMapActionsCallbackInterface.OnScrollMap;
                @ScrollMap.performed -= m_Wrapper.m_MapMapActionsCallbackInterface.OnScrollMap;
                @ScrollMap.canceled -= m_Wrapper.m_MapMapActionsCallbackInterface.OnScrollMap;
            }
            m_Wrapper.m_MapMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @CloseMap.started += instance.OnCloseMap;
                @CloseMap.performed += instance.OnCloseMap;
                @CloseMap.canceled += instance.OnCloseMap;
                @ScrollMap.started += instance.OnScrollMap;
                @ScrollMap.performed += instance.OnScrollMap;
                @ScrollMap.canceled += instance.OnScrollMap;
            }
        }
    }
    public MapMapActions @MapMap => new MapMapActions(this);
    public interface IPlayerMapActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnAimMode(InputAction.CallbackContext context);
        void OnFireProjectile(InputAction.CallbackContext context);
        void OnGrapple(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
        void OnOpenMenu(InputAction.CallbackContext context);
        void OnOpenDevMenu(InputAction.CallbackContext context);
        void OnOpenMap(InputAction.CallbackContext context);
    }
    public interface ITestMapActions
    {
        void OnVector2(InputAction.CallbackContext context);
    }
    public interface IPauseMapActions
    {
        void OnCloseMenu(InputAction.CallbackContext context);
    }
    public interface IMapMapActions
    {
        void OnCloseMap(InputAction.CallbackContext context);
        void OnScrollMap(InputAction.CallbackContext context);
    }
}
